import {  VerticalBox, HorizontalBox, TabWidget, Palette } from "std-widgets.slint";
import {Button} from "./components/Button.slint";
import "./fonts/GeistMono/GeistMono-Black.otf";
import "./fonts/GeistMono/GeistMono-Bold.otf";
import "./fonts/GeistMono/GeistMono-Light.otf";
import "./fonts/GeistMono/GeistMono-Medium.otf";
import "./fonts/GeistMono/GeistMono-Regular.otf";
import "./fonts/GeistMono/GeistMono-SemiBold.otf";
import "./fonts/GeistMono/GeistMono-Thin.otf";
import "./fonts/GeistMono/GeistMono-UltraBlack.otf";
import "./fonts/GeistMono/GeistMono-UltraLight.otf";

export component AppWindow inherits Window {
    no-frame: false;
    title: "Slint";
    default-font-family: "Geist Mono";
    background: #0d0d0d;
    in-out property <int> counter: 42;
    callback request-increase-value();
    callback request-decrease-value();

    VerticalBox {

        HorizontalBox {
            alignment: stretch;
            horizontal-stretch: 1;
            vertical-stretch: 1;

            Rectangle {
                vertical-stretch: 1;
                horizontal-stretch: 1;
                border-radius: 2px;
                background: rgba(255, 255, 255, 0.1);
                HorizontalBox {
                    vertical-stretch: 1;
                    horizontal-stretch: 1;
                    alignment: start;
                    Text {
                        color: rgba(255,255,255,0.75);
                        vertical-stretch: 0;
                        text: "Counter: \{root.counter}";
                    }
                }
            }
        }

        HorizontalBox {
            vertical-stretch: 0;
            Button {
                vertical-stretch: 0;

                text: "Decrease value";
                clicked => {
                    root.request-decrease-value();
                }
            }

            Button {
                vertical-stretch: 0;

                text: "Increase value";
                clicked => {
                    root.request-increase-value();
                }
            }
        }
    }
}
